/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sE2;

import ProffSkillsAssignment1.Course;
import ProffSkillsAssignment1.Student;
import java.time.LocalDate;
import java.time.Month;
import java.util.ArrayList;
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Driver d = new Driver();
        
        ArrayList<Course> courseList = d.getCourse();
        ArrayList<Student> students = d.getStudents();
        
        System.out.println("*******Courses**********\n");
        for(Course c: courseList){
            
            System.out.println(c);
            System.out.println("\n");
            
        }
        System.out.println("*******Students**********\n");
        for(Student s: students){
            
            System.out.println(s);
            System.out.println("\n");
            
        }
        
       
            
        }
    
    
}
